version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: gateway
    restart: always
    network_mode: "host"
    ports:
      - 8080:8080
  autoparts1:
    build:
      context: .
      dockerfile: autoparts1/Dockerfile
    image: autoparts1
    restart: always
    network_mode: "host"
    ports:
      - 8081:8081
