server:
  port: 0
  servlet:
    context-path: /part

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application.name: part-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5432/part
    username: part_service
    password: prt-srv
  jpa:
    database-platform: org.hibernate.
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  sql:
    init:
      platform: mysql
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka